export const appTopics = [
  {
    name: "ECONOMY",
    threshold: 2.0,
    exclusions: ["funeral", "memorial", "obituary", "death"],
    keywords: [
      { keyword: "inflation", weight: 2.0 },
      { keyword: "cost of living", weight: 3.0 },
      { keyword: "cost of living crisis", weight: 3.0 },
      { keyword: "tax", weight: 1.5 },
      { keyword: "wealth", weight: 1.5 },
      { keyword: "budget", weight: 1.5 },
      { keyword: "recession", weight: 2.0 },
      { keyword: "housing", weight: 2.0 },
      { keyword: "rent", weight: 1.5 },
      { keyword: "mortgage", weight: 2.0 },
      { keyword: "economy", weight: 1.0 },
      { keyword: "economic", weight: 1.0 },
      { keyword: "market", weight: 1.0 },
      { keyword: "trade", weight: 1.0 }
    ]
  },
  {
    name: "ENVIRONMENT",
    threshold: 2.0,
    exclusions: ["sport", "recreation", "hiking", "camping"],
    keywords: [
      { keyword: "climate crisis", weight: 3.0 },
      { keyword: "climate emergency", weight: 3.0 },
      { keyword: "global warming", weight: 2.5 },
      { keyword: "renewable", weight: 2.0 },
      { keyword: "renewable energy", weight: 2.5 },
      { keyword: "solar", weight: 1.5 },
      { keyword: "wind energy", weight: 2.0 },
      { keyword: "biodiversity", weight: 2.0 },
      { keyword: "deforestation", weight: 2.0 },
      { keyword: "emissions", weight: 1.5 },
      { keyword: "coal", weight: 1.5 },
      { keyword: "gas", weight: 1.0 },
      { keyword: "fossil fuel", weight: 2.0 },
      { keyword: "fossil fuels", weight: 2.0 },
      { keyword: "environment", weight: 1.0 },
      { keyword: "environmental", weight: 1.0 },
      { keyword: "climate", weight: 1.0 },
      { keyword: "wildfire", weight: 1.5 },
      { keyword: "bushfire", weight: 1.5 }
    ]
  },
  {
    name: "FIRST NATIONS",
    threshold: 1.5,
    exclusions: ["sport", "cricket", "football", "rugby"],
    keywords: [
      { keyword: "treaty", weight: 2.5 },
      { keyword: "voice", weight: 1.5 },
      { keyword: "maiden parliamentary speech", weight: 2.0 },
      { keyword: "first nations", weight: 2.0 },
      { keyword: "indigenous", weight: 1.5 },
      { keyword: "aboriginal", weight: 1.5 },
      { keyword: "torres strait islander", weight: 2.0 },
      { keyword: "torres strait islanders", weight: 2.0 },
      { keyword: "native title", weight: 2.0 },
      { keyword: "stolen generations", weight: 2.0 },
      { keyword: "genocide", weight: 2.0 },
      { keyword: "survivors", weight: 1.0 },
      { keyword: "national", weight: 0.5 }
    ]
  },
  {
    name: "INTERNATIONAL",
    threshold: 2.0,
    exclusions: ["olympic", "olympics", "sport", "cricket", "football", "rugby", "tennis"],
    keywords: [
      { keyword: "gaza", weight: 2.5 },
      { keyword: "palestine", weight: 2.0 },
      { keyword: "israel", weight: 1.5 },
      { keyword: "march for freedom", weight: 2.5 },
      { keyword: "ukraine", weight: 2.0 },
      { keyword: "war", weight: 1.5 },
      { keyword: "imperialism", weight: 2.0 },
      { keyword: "nato", weight: 1.5 },
      { keyword: "military", weight: 1.0 },
      { keyword: "occupation", weight: 1.5 },
      { keyword: "refugee", weight: 1.5 },
      { keyword: "refugees", weight: 1.5 },
      { keyword: "sanction", weight: 1.5 },
      { keyword: "sanctions", weight: 1.5 },
      { keyword: "middle east", weight: 1.5 },
      { keyword: "china", weight: 1.0 },
      { keyword: "usa", weight: 1.0 },
      { keyword: "united states", weight: 1.0 },
      { keyword: "europe", weight: 1.0 }
    ]
  },
  {
    name: "LABOUR",
    threshold: 2.0,
    exclusions: ["funeral", "memorial", "obituary", "death", "sport"],
    keywords: [
      { keyword: "cfmeu", weight: 2.5 },
      { keyword: "construction", weight: 1.0 },
      { keyword: "builders labour", weight: 2.5 },
      { keyword: "industrial", weight: 1.5 },
      { keyword: "industrial action", weight: 2.5 },
      { keyword: "industrial relations", weight: 2.0 },
      { keyword: "fair work", weight: 1.5 },
      { keyword: "award", weight: 1.0 },
      { keyword: "awards", weight: 1.0 },
      { keyword: "enterprise agreement", weight: 2.0 },
      { keyword: "enterprise agreements", weight: 2.0 },
      { keyword: "registered architect", weight: 1.0 },
      { keyword: "labour", weight: 1.0 },
      { keyword: "worker", weight: 1.0 },
      { keyword: "workers", weight: 1.0 },
      { keyword: "union", weight: 1.0 },
      { keyword: "unions", weight: 1.0 },
      { keyword: "strike", weight: 1.5 },
      { keyword: "wage", weight: 1.0 },
      { keyword: "wages", weight: 1.0 },
      { keyword: "pay", weight: 0.5 },
      { keyword: "pay rise", weight: 2.0 },
      { keyword: "pay rises", weight: 2.0 },
      { keyword: "minimum wage", weight: 2.0 },
      { keyword: "casual", weight: 1.0 },
      { keyword: "casualisation", weight: 2.0 },
      { keyword: "casual work", weight: 1.5 },
      { keyword: "full time", weight: 0.5 },
      { keyword: "full-time", weight: 0.5 },
      { keyword: "permanent", weight: 0.5 },
      { keyword: "job", weight: 0.5 },
      { keyword: "jobs", weight: 0.5 },
      { keyword: "employment", weight: 0.5 },
      { keyword: "unemployment", weight: 1.0 },
      { keyword: "layoff", weight: 1.5 },
      { keyword: "layoffs", weight: 1.5 },
      { keyword: "redundancy", weight: 1.5 },
      { keyword: "redundancies", weight: 1.5 },
      { keyword: "job cut", weight: 1.5 },
      { keyword: "job cuts", weight: 1.5 },
      { keyword: "job security", weight: 2.0 },
      { keyword: "workplace", weight: 0.5 },
      { keyword: "workplace safety", weight: 1.5 },
      { keyword: "safe work", weight: 1.5 },
      { keyword: "health and safety", weight: 1.5 },
      { keyword: "ohs", weight: 1.0 },
      { keyword: "whs", weight: 1.0 },
      { keyword: "lockout", weight: 2.0 },
      { keyword: "lock-out", weight: 2.0 },
      { keyword: "closed shop", weight: 2.0 },
      { keyword: "roster", weight: 0.5 },
      { keyword: "rosters", weight: 0.5 },
      { keyword: "shift", weight: 0.5 },
      { keyword: "shifts", weight: 0.5 },
      { keyword: "overtime", weight: 1.5 },
      { keyword: "penalty", weight: 1.0 },
      { keyword: "penalties", weight: 1.0 },
      { keyword: "entitlement", weight: 1.0 },
      { keyword: "entitlements", weight: 1.0 },
      { keyword: "agreement", weight: 0.5 },
      { keyword: "agreements", weight: 0.5 },
      { keyword: "negotiation", weight: 1.5 },
      { keyword: "negotiations", weight: 1.5 },
      { keyword: "collective", weight: 1.0 },
      { keyword: "collective bargaining", weight: 2.0 },
      { keyword: "employer", weight: 0.5 },
      { keyword: "employers", weight: 0.5 },
      { keyword: "corporation", weight: 0.5 },
      { keyword: "companies", weight: 0.5 },
      { keyword: "company", weight: 0.5 },
      { keyword: "private", weight: 0.5 },
      { keyword: "privatisation", weight: 2.0 },
      { keyword: "privatization", weight: 2.0 },
      { keyword: "privatise", weight: 2.0 },
      { keyword: "privatize", weight: 2.0 },
      { keyword: "contractor", weight: 1.0 },
      { keyword: "contractors", weight: 1.0 },
      { keyword: "labour hire", weight: 2.0 },
      { keyword: "labour-hire", weight: 2.0 },
      { keyword: "exploitation", weight: 2.0 },
      { keyword: "exploited", weight: 2.0 },
      { keyword: "decent rights", weight: 2.0 },
      { keyword: "decent jobs", weight: 2.0 },
      { keyword: "standard", weight: 0.5 },
      { keyword: "standards", weight: 0.5 },
      { keyword: "rights", weight: 0.5 },
      { keyword: "worker rights", weight: 2.0 },
      { keyword: "worker's rights", weight: 2.0 },
      { keyword: "unionism", weight: 1.5 },
      { keyword: "unionize", weight: 1.5 },
      { keyword: "unionise", weight: 1.5 },
      { keyword: "organize", weight: 1.0 },
      { keyword: "organise", weight: 1.0 },
      { keyword: "solidarity", weight: 1.5 }
    ]
  },
  {
    name: "MUTUAL AID",
    threshold: 2.0,
    exclusions: ["sport", "recreation"],
    keywords: [
      { keyword: "mutual aid", weight: 3.0 },
      { keyword: "solidarity", weight: 2.0 },
      { keyword: "community", weight: 1.0 },
      { keyword: "co-op", weight: 2.0 },
      { keyword: "cooperative", weight: 2.0 },
      { keyword: "cooperatives", weight: 2.0 },
      { keyword: "food share", weight: 2.0 },
      { keyword: "free food", weight: 2.0 },
      { keyword: "food relief", weight: 2.0 },
      { keyword: "food bank", weight: 2.0 },
      { keyword: "rent relief", weight: 2.0 },
      { keyword: "rent crisis", weight: 2.0 },
      { keyword: "eviction", weight: 2.0 },
      { keyword: "evictions", weight: 2.0 },
      { keyword: "homeless", weight: 1.5 },
      { keyword: "homelessness", weight: 2.0 },
      { keyword: "housing crisis", weight: 2.0 },
      { keyword: "social housing", weight: 2.0 },
      { keyword: "affordable housing", weight: 2.0 },
      { keyword: "charity", weight: 1.0 },
      { keyword: "charitable", weight: 1.0 }
    ]
  },
  {
    name: "PARLIAMENT",
    threshold: 2.0,
    exclusions: ["olympic", "olympics", "sport", "cricket", "football", "rugby", "tennis", "funeral", "memorial"],
    keywords: [
      { keyword: "albanese", weight: 2.0 },
      { keyword: "dutton", weight: 2.0 },
      { keyword: "labor", weight: 1.5 },
      { keyword: "liberal", weight: 1.0 },
      { keyword: "national", weight: 1.0 },
      { keyword: "green", weight: 1.0 },
      { keyword: "teal", weight: 1.5 },
      { keyword: "parliament", weight: 1.5 },
      { keyword: "parliamentary", weight: 1.5 },
      { keyword: "government", weight: 1.0 },
      { keyword: "senate", weight: 1.5 },
      { keyword: "election", weight: 1.5 },
      { keyword: "elections", weight: 1.5 },
      { keyword: "bill", weight: 1.5 },
      { keyword: "bills", weight: 1.5 },
      { keyword: "legislation", weight: 1.5 },
      { keyword: "policy", weight: 1.0 },
      { keyword: "policies", weight: 1.0 },
      { keyword: "minister", weight: 1.0 },
      { keyword: "ministers", weight: 1.0 },
      { keyword: "mp", weight: 1.0 },
      { keyword: "mps", weight: 1.0 },
      { keyword: "seat", weight: 0.5 },
      { keyword: "seats", weight: 0.5 },
      { keyword: "poll", weight: 1.0 },
      { keyword: "polls", weight: 1.0 },
      { keyword: "preference", weight: 1.0 },
      { keyword: "preferences", weight: 1.0 },
      { keyword: "two-party", weight: 1.5 },
      { keyword: "preferential", weight: 1.0 },
      { keyword: "campaign", weight: 1.0 },
      { keyword: "campaigning", weight: 1.0 },
      { keyword: "rally", weight: 1.0 },
      { keyword: "rallies", weight: 1.0 }
    ]
  },
  {
    name: "PRAXIS",
    threshold: 2.0,
    exclusions: ["sport", "recreation", "funeral", "memorial"],
    keywords: [
      { keyword: "protest", weight: 2.0 },
      { keyword: "protests", weight: 2.0 },
      { keyword: "activism", weight: 2.0 },
      { keyword: "activist", weight: 1.5 },
      { keyword: "activists", weight: 1.5 },
      { keyword: "demonstration", weight: 2.0 },
      { keyword: "demonstrations", weight: 2.0 },
      { keyword: "rally", weight: 1.5 },
      { keyword: "rallies", weight: 1.5 },
      { keyword: "march", weight: 1.5 },
      { keyword: "marching", weight: 1.5 },
      { keyword: "occupation", weight: 1.5 },
      { keyword: "occupy", weight: 1.5 },
      { keyword: "occupying", weight: 1.5 },
      { keyword: "sit-in", weight: 2.0 },
      { keyword: "sit in", weight: 2.0 },
      { keyword: "blockade", weight: 2.0 },
      { keyword: "blockading", weight: 2.0 },
      { keyword: "picket", weight: 2.0 },
      { keyword: "picketing", weight: 2.0 },
      { keyword: "pickets", weight: 2.0 },
      { keyword: "civil disobedience", weight: 2.5 },
      { keyword: "resistance", weight: 1.5 },
      { keyword: "resisting", weight: 1.5 },
      { keyword: "uprising", weight: 2.0 },
      { keyword: "revolution", weight: 1.5 },
      { keyword: "revolutionary", weight: 1.5 },
      { keyword: "solidarity", weight: 1.5 },
      { keyword: "organize", weight: 1.0 },
      { keyword: "organise", weight: 1.0 },
      { keyword: "organizing", weight: 1.0 },
      { keyword: "organising", weight: 1.0 }
    ]
  },
  {
    name: "TECHNOLOGY",
    threshold: 2.0,
    exclusions: ["app", "application", "software", "digital", "online", "website", "gadget", "device", "phone", "mobile", "computer", "internet", "social media", "platform", "robot", "blockchain", "crypto", "nft", "metaverse", "virtual reality", "augmented reality", "cloud", "server", "hack", "malware", "virus", "gdpr", "facial recognition", "biometric"],
    keywords: [
      { keyword: "technology", weight: 1.5 },
      { keyword: "artificial intelligence", weight: 3.0 },
      { keyword: "ai", weight: 2.0 },
      { keyword: "machine learning", weight: 2.5 },
      { keyword: "automation", weight: 2.0 },
      { keyword: "robotics", weight: 2.0 },
      { keyword: "surveillance", weight: 2.0 },
      { keyword: "privacy", weight: 1.5 },
      { keyword: "cybersecurity", weight: 2.0 },
      { keyword: "cyber", weight: 1.0 },
      { keyword: "data", weight: 0.5 },
      { keyword: "tech", weight: 1.0 },
      { keyword: "startup", weight: 1.0 },
      { keyword: "innovation", weight: 1.0 },
      { keyword: "tech regulation", weight: 2.0 },
      { keyword: "big tech", weight: 2.0 },
      { keyword: "silicon valley", weight: 1.5 }
    ]
  }
];