export const appFeeds = {
  coreSources: {
    "https://www.3cr.org.au/news.xml": "3CR",
    "https://arena.org.au/feed": "ARENA",
    "https://www.blackpeoplesunion.org/articles/rss.xml": "BLACK PEOPLES UNION",
    "https://www.blackpeoplesunion.org/statements/rss.xml": "BLACK PEOPLES UNION",
    "https://www.thenews.coop/country/oceania/feed": "CO-OP NEWS",
    "https://disputesreport.substack.com/feed": "DISPUTES REPORT",
    "https://revaus.org/category/australian-politics/feed": "EUREKA INITIATIVE",
    "https://freedomnews.org.uk/tag/australia/feed": "FREEDOM",
    "https://www.greenleft.org.au/rss.xml": "GREEN LEFT",
    "https://seqldiww.org/category/australia/feed": "IWW (SOUTH EAST QUEENSLAND)",
    "https://indigenousx.com.au/stories/feed": "INDIGENOUSX",
    "https://koorimail.com/feed": "KOORI MAIL",
    "https://labortribune.net.au/feed": "LABOR TRIBUNE",
    "https://www.labourstart.org/rss/labourstart.au.xml": "LABOURSTART",
    "https://www.auscp.org.au/militant-worker/rss.xml": "MILITANT WORKER",
    "https://oaf.org.au/blog/feed": "OPENAUSTRALIA FOUNDATION",
    "https://overland.org.au/latest/feed": "OVERLAND",
    "https://partisanmagazine.org/feed/": "PARTISAN!",
    "https://ancomfed.org/picket-line/feed": "PICKET LINE",
    "https://redantcollective.org/feed": "RED ANT",
    "https://redflag.org.au/rss/": "RED FLAG",
    "https://red-spark.org/tag/australia/feed": "RED SPARK",
    "https://rahu.org.au/category/articles/feed": "RENTERS & HOUSING UNION",
    "https://www.search.org.au/search_news.rss": "SEARCH FOUNDATION",
    "https://socialismtoday.au/feed": "SOCIALISM TODAY",
    "https://solidarity.net.au/feed": "SOLIDARITY",
    "https://au.spiritofeureka.org/category/fp-roktabs-showcase/feed": "SPIRIT OF EUREKA",
    "https://temokalati.wordpress.com/feed": "TEMOKALATI",
    "https://melbacg.au/category/anvil/rss": "THE ANVIL",
    "https://communist.org.au/feed": "THE COMMUNIST",
    "https://cpa.org.au/feed/?post_type=guardian": "THE GUARDIAN (CPA)",
    "https://vanguard-cpaml.blogspot.com/rss.xml": "VANGUARD",
    "https://www.wsws.org/en/topics/country/australia/rss.xml": "WORLD SOCIALIST WEB SITE"
  },
  globalSources: {
    "https://jacobin.com/feed": "JACOBIN",
    "https://www.counterpunch.org/feed": "COUNTER PUNCH",
    "https://themilitant.com/feed": "THE MILITANT"
  },
  extendedSources: {
    "https://michaelwest.com.au/category/latest-posts/feed/": "MICHAEL WEST",
    "http://feeds.feedburner.com/IndependentAustralia": "INDEPENDENT AUSTRALIA",
    "https://theconversation.com/topics/australia-64/articles.atom": "THE CONVERSATION",
    "https://www.theguardian.com/australia-news/australian-trade-unions/rss": "THE GUARDIAN (GNM)"
  },
  auKeywords: [
    "australia", "australian", "new south wales", "nsw", "sydney", "victoria", "vic", "melbourne",
    "queensland", "qld", "brisbane", "western australia", "wa", "perth", "south australia", "sa",
    "adelaide", "tasmania", "tas", "hobart", "act", "canberra", "nt", "darwin"
  ],
  
  // Map the exact publisher name to the filename inside static/logos/
  // Example: "GREEN LEFT": "greenleft-logo.png"
  publisherLogos: {
    "3CR": "3CR.jpg",
    "ARENA": "",
    "BLACK PEOPLES UNION": "",
    "CO-OP NEWS": "CO-OP_NEWS.jpg",
    "DISPUTES REPORT": "",
    "EUREKA INITIATIVE": "",
    "FREEDOM": "",
    "GREEN LEFT": "GREEN_LEFT.jpg",
    "IWW (SOUTH EAST QUEENSLAND)": "",
    "INDIGENOUSX": "INDIGENOUSX.jpg",
    "KOORI MAIL": "KOORI_MAIL.jpg",
    "LABOR TRIBUNE": "LABOR_TRIBUNE.jpg",
    "LABOURSTART": "LABOURSTART.jpg",
    "MILITANT WORKER": "",
    "OPENAUSTRALIA FOUNDATION": "OPENAUSTRALIA_FOUNDATION.jpg",
    "OVERLAND": "OVERLAND.jpg",
    "PARTISAN!": "PARTISAN.jpg",
    "PICKET LINE": "PICKET_LINE.jpg",
    "RED ANT": "",
    "RED FLAG": "RED_FLAG.jpg",
    "RED SPARK": "RED_SPARK.jpg",
    "RENTERS & HOUSING UNION": "RENTERS_&_HOUSING_UNION.jpg",
    "SEARCH FOUNDATION": "SEARCH_FOUNDATION.jpg",
    "SOCIALISM TODAY": "",
    "SOLIDARITY": "",
    "SPIRIT OF EUREKA": "SPIRIT_OF_EUREKA.jpg",
    "TEMOKALATI": "TEMOKALATI.jpg",
    "THE ANVIL": "",
    "THE COMMUNIST": "",
    "THE GUARDIAN (CPA)": "THE_GUARDIAN_(CPA).jpg",
    "VANGUARD": "",
    "WORLD SOCIALIST WEB SITE": "WORLD_SOCIALIST_WEB_SITE.jpg",
    // Global sources
    "COUNTER PUNCH": "",
    "JACOBIN": "JACOBIN.jpg",
    "THE MILITANT": "",
    // Extended sources
    "MICHAEL WEST": "",
    "INDEPENDENT AUSTRALIA": "",
    "THE CONVERSATION": "",
    "THE GUARDIAN (GNM)": ""
  }
};